### ISSUE TITLE
Fix the WinSW release flow and release 2.4.0

### ISSUE THREAD

**Issue by oleg-nenashev** [winsw/winsw#378]
https://github.com/kohsuke/winsw/commit/6e9d25a7b53a373049936caa34a2fce3edb7afc2 from @NextTurn apparently broke the release job in https://ci.appveyor.com/project/oleg-nenashev/winsw-g2fwp . It uses `appveyor.yml` but sets the arbitrary version. https://github.com/kohsuke/winsw/commit/6e9d25a7b53a373049936caa34a2fce3edb7afc2 sets the version in config-as-code, and hence it overrides the setting in the job.

My next steps:

- [ ] Move the release Pipeline and deployments to configuration-as-code
- [ ] TBD: Switch to the 4-digit versioning scheme (`major.minor.patch.build`)
- [ ] Fix the Pipeline so that it can release the versions
- [ ] Get 2.4.0 released

**Comment by oleg-nenashev** [comment]
Current WinSW Release Job YAML:

```
version: 2.{build}.0
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
build:
  verbosity: minimal
deploy: off
```

The most of the configs come from appveyor YAML.

Most likely I will change the release flow so that different versioning is applied on tags
