### ISSUE TITLE
Runaway Process Killer doesn't expand %BASE%

### ISSUE THREAD

**Issue by offa** [winsw/winsw#667]
Unlike it's XML configuration, the Yaml configuration seems not to expand the `%BASE%` variable.

## Steps to reproduce

Minimal service with an `pidfile` path containing `%BASE%`:

```yml
id: example-service
name: Example service
description: Example.
executable: '%BASE%\example.bat' # Expands correctly

extensions:
    - id: killRunawayProcess
      enabled: yes
      className: WinSW.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension
      settings:
            pidfile: '%BASE%/example.pid' # Uses %BASE%
            stopTimeOut: 5000
            StopParentFirst: true
```

Install and start the service.

###### Wrapper log:

```
INFO  - Recording PID of the started process:8896. PID file destination is %BASE%/example.pid
ERROR - Cannot update the PID file %BASE%/example.pid
```
Followed by a related `System.IO.DirectoryNotFoundException`.

## Environment

* WinSW version: 2.10.1
* WinSW package type: .NET 4.6.1
* Windows version: 10
* Wrapped executable and version: Any

## Possible Solution

Probably only a missing variable expansion.
