### ISSUE TITLE
The serviceaccount settings doesn't work, but serviceAccount does

### ISSUE THREAD

**Issue by jakubgs** [winsw/winsw#839]
## Summary

I'm using WinSW with the YAML config format, and using `serviceaccount` does not work:

![image](https://user-images.githubusercontent.com/2212681/122741439-3f55c100-d285-11eb-8b5e-e0ba53be87d6.png)

But switching it to `serviceAccount` makes it create the Log on configuration correctly:

![image](https://user-images.githubusercontent.com/2212681/122741578-601e1680-d285-11eb-8fa4-30b182d88854.png)

Which wasted quite a lot of time for me, because both documentation:
https://github.com/winsw/winsw/blob/v2.11.0/doc/yamlConfigFile.md#service-account

And example use the lower case version:
https://github.com/winsw/winsw/blob/e380e6c64e961c77e679f16bb315aa9f88fe289a/examples/sample-allOption.yml#L5-L9

## Environment

* WinSW version: `2.11.0`
* WinSW package type: .NET 4.6.1
* Windows version: Windows Server 2019 Datacenter
* Wrapped executable and version: irrelevant

## Possible Solution
Fix the parsing to either accept lower case name, or fix docs and examples to use the upper case version.

**Comment by Agent-Birkhoff** [comment]
When using xml, neither of serviceaccount nor serviceAccount work...
HUGE bug

**Comment by Agent-Birkhoff** [comment]
When using xml, neither serviceAccount nor serviceaccount work...

**Comment by Agent-Birkhoff** [comment]
> When using xml, neither serviceAccount nor serviceaccount work...
```
<serviceaccount>
  <username>NT AUTHORITY\NetworkService</username>
</serviceaccount>
```

**Comment by nxtn** [comment]
Hi @Agent-Birkhoff, please refer to the following docs for the version you used.

3.x: https://github.com/winsw/winsw/blob/v3/docs/xml-config-file.md#service-account

2.x: https://github.com/winsw/winsw/blob/master/doc/xmlConfigFile.md#service-account

**Comment by jakubgs** [comment]
@nxtn I am NOT using v3. I'm using `v2.11.0`:
```yaml
winsw_service_wrapper_version: 'v2.11.0'
winsw_service_wrapper_url: 'https://github.com/winsw/winsw/releases/download/{{ winsw_service_wrapper_version }}/WinSW.NET461.exe'
winsw_service_wrapper_sha256: 'fa65df592bac031f1c647664450e35968b01023c'
```
https://github.com/status-im/infra-role-winsw/blob/44f335715fda2e0ba1b2cb2b815389e05c5ae0b1/defaults/main.yml#L36-L38

Please reopen this issue.
