### ISSUE TITLE
The allowservicelogon setting is being ignored

### ISSUE THREAD

**Issue by jakubgs** [winsw/winsw#840]
## Summary

I'm using WinSW with YAML configuration and setting `allowservicelogon: true`, but it doesn't work:
```
2021-06-21 09:22:06,447 INFO  - Starting service 'My Cool Service (my-cool-service)'...
2021-06-21 09:22:06,447 FATAL - Cannot start service my-cool-service on computer '.'.
```
Which shows this error when started by hand from `Services`:
![image](https://user-images.githubusercontent.com/2212681/122742338-213c9080-d286-11eb-8bd8-2b18469fd739.png)

But when I go into `Log On` settings and update the password and click `Apply` I get this dialog:
![image](https://user-images.githubusercontent.com/2212681/122742406-34e7f700-d286-11eb-9145-6b5062aa8ea7.png)

Which means that `allowservicelogon` has no effect for some reason.

## Steps to reproduce

Just try to use the `allowservicelogon` setting inside of `serviceAccount`:
```yaml
---
id: 'my-cool-service'
name: 'My Cool Service'
description: 'Some kind of description'
stoptimeout: 10
priority: 'normal'
serviceAccount:
  domain: 'MYHOST'
  user: 'myuser'
  password: 'super-secret-password'
  allowservicelogon: true
env:
workingdirectory: 'C:/Users/myuser/my-cool-service'
executable: 'C:/Users/myuser/my-cool-service/bin/coolservice.exe'
arguments: '--whatever'
```

## Environment

* WinSW version: `2.11.0`
* WinSW package type: .NET 4.6.1
* Windows version: Windows Server 2019 Datacenter
* Wrapped executable and version: irrelevant
