### ISSUE TITLE
Setting the workingdirectory doesn't seem to work correclty

### ISSUE THREAD

**Issue by Bios-Marcel** [winsw/winsw#855]
Setting the `workingdirectory` key seems to not have any effect. Instead it uses the location of the `winsw.exe`.

## Steps to reproduce

```yaml
id: apmserver
name: APM Server
description: TODO

workingdirectory: 'C:\Program Files\APM Server\servicesteuerung\..'
executable: 'C:\Program Files\APM Server\servicesteuerung\..\jre\bin\java.exe'
arguments: '-jar "C:\Program Files\APM Server\servicesteuerung\..\Advantage-PM Server.jar"'
```

The `java` executable and the `.jar` file are both being called correctly, however, the working directory is always `C:\Program Files\APM Server\servicesteuerung` instead of `C:\Program Files\APM Server`, which is what 'C:\Program Files\APM Server\servicesteuerung\..` should resolve to. This causes the application to access incorrect directories during runtime.

## Environment

* WinSW version: 2.11
* WinSW package type: WinSW-x64.exe
* Windows version: WIndows 10
